### ISSUE TITLE
Add Ability to Handle Spherical Densiometer Readings at Non-Standard Locations

### ISSUE THREAD

**Issue by hmthomas** [NCPN/upland#110]
Spherical densiometer readings are normally taken at five fixed locations: 5, 15, 25, 35, and 45 meters. However, there are times when measurements cannot be taken at these standard locations (e.g., a reading may need to be taken at 5.5 m instead of 5 m). When this happens currently, it is documented in the visit comments. It is desired to have a better way to record it in the database.

I would label this as "investigate" and/or assign it a low priority.

**Comment by blcampbell-NCPN** [comment]
**Possible solutions:** 
- Change point dropdowns to textboxes
- Allow edits to current comboboxes (favored approach)

**Important**
Careful consideration is needed as it requires additional code to limit entries to avoid invalid values.

*Deferring for future development.*
