### ISSUE TITLE
Add Sapling Null Check Query to Plot Check Form

### ISSUE THREAD

**Issue by hmthomas** [NCPN/upland#116]
A QC query will be added to check for missing sapling totals after the field season. It would be helpful to have the crew also run this query at the end of a plot, but only if it doesn't exacerbate the "too many databases open" issue.

The query checks for records with any null totals or all zero totals (see below). Since this query has not yet been thoroughly tested, it should be considered a placeholder.

 SELECT tbl_Locations.Unit_Code, tbl_Locations.Plot_ID, tbl_Locations.Vegetation_Type, tbl_Events.Start_Date, IIf([tlu_NCPN_Plants]![LU_Code] Is Null,[tbl_OT_Tree_Saplings]![Species],[tlu_NCPN_Plants]![LU_Code]) AS Species_Code, tlu_NCPN_Plants.Utah_Species, tbl_OT_Tree_Saplings.Alive, tbl_OT_Tree_Saplings.D25, tbl_OT_Tree_Saplings.D51, tbl_OT_Tree_Saplings.D101
FROM ((tbl_Locations INNER JOIN tbl_Events ON tbl_Locations.Location_ID = tbl_Events.Location_ID) INNER JOIN tbl_OT_Tree_Saplings ON tbl_Events.Event_ID = tbl_OT_Tree_Saplings.Event_ID) LEFT JOIN tlu_NCPN_Plants ON tbl_OT_Tree_Saplings.Species = tlu_NCPN_Plants.Master_PLANT_Code
WHERE (tbl_OT_Tree_Saplings.D25 Is Null) OR (tbl_OT_Tree_Saplings.D51 Is Null) OR (tbl_OT_Tree_Saplings.D101 Is Null) OR ((tbl_OT_Tree_Saplings.D25=0) AND (tbl_OT_Tree_Saplings.D51=0) AND (tbl_OT_Tree_Saplings.D101=0))
ORDER BY tbl_Locations.Unit_Code, tbl_Locations.Plot_ID, tbl_Events.Start_Date, IIf([tlu_NCPN_Plants]![LU_Code] Is Null,[tbl_OT_Tree_Saplings]![Species],[tlu_NCPN_Plants]![LU_Code]), tbl_OT_Tree_Saplings.Alive;

**Comment by blcampbell-NCPN** [comment]
closed this in [5153f92](https://github.com/NCPN/upland/commit/5153f92bb872764b5e03677a84e19b07d8b07e7f)
