### ISSUE TITLE
Add Exotic Frequency Null Species Check Query to Plot Check Form

### ISSUE THREAD

**Issue by hmthomas** [NCPN/upland#117]
A post field season QC query will be added to check for exotic frequency records with no species. It would be helpful to have the crew also run this query at the end of a plot, but only if it doesn't exacerbate the "too many databases open" issue.

The SQL is below. Since this query has not yet been thoroughly tested, it should be considered a placeholder.

SELECT tbl_Locations.Unit_Code, tbl_Locations.Plot_ID, tbl_Locations.Vegetation_Type, tbl_Events.Start_Date, tbl_LP_Belt_Transect.Transect
FROM (tbl_Locations INNER JOIN (tbl_Events INNER JOIN tbl_LP_Belt_Transect ON tbl_Events.Event_ID = tbl_LP_Belt_Transect.Event_ID) ON tbl_Locations.Location_ID = tbl_Events.Location_ID) INNER JOIN tbl_LP_Exotic_Freq ON tbl_LP_Belt_Transect.Transect_ID = tbl_LP_Exotic_Freq.Transect_ID
WHERE (tbl_LP_Exotic_Freq.Species Is Null Or (tbl_LP_Exotic_Freq.Species="") Or (tbl_LP_Exotic_Freq.Species)=" ")
ORDER BY tbl_Locations.Unit_Code, tbl_Locations.Plot_ID, tbl_Events.Start_Date, tbl_LP_Belt_Transect.Transect;

**Comment by blcampbell-NCPN** [comment]
closed this in [5153f92](https://github.com/NCPN/upland/commit/5153f92bb872764b5e03677a84e19b07d8b07e7f)
