### ISSUE TITLE
Enhance Gap UI to Check for Null Gap Start or End

### ISSUE THREAD

**Issue by hmthomas** [NCPN/upland#118]
It is desired to have a button on the gap form(s) to check for null gap start or gap end. The button would be used immediately after sampling to let the user know whether any gap start or end values are missing. This functionality is desired for both basal and canopy gaps. It could be implemented similarly to the _Verify Soil Surface_ button on the point intercept form.

**Comment by blcampbell-NCPN** [comment]
NULL issues appeared in years prior to current database. Closing as no longer applicable, won't fix.
