### ISSUE TITLE
Sapling and Shrub Plot Check Queries Display Data from All Plots

### ISSUE THREAD

**Issue by hmthomas** [NCPN/upland#121]
The sapling and shrub plot check queries (qc_missing_sapling_totals and qc_missing_shrub_totals, respectively) do not filter out records from other plots, so records from all plots are displayed. 

This issue can be re-created with the master test backend using most any plot visit. The screen captures below show the results of the sapling and shrub queries for the ARCH 4, 4/5/2016 visit.

![image](https://user-images.githubusercontent.com/6645997/38206340-4d54df88-3667-11e8-9806-e06852ce7e83.png)

![image](https://user-images.githubusercontent.com/6645997/38206343-53d75372-3667-11e8-8be0-8bb57867ff09.png)

This is a low priority issue as the crews should not encounter it often and it should not impact their work.

**Comment by blcampbell-NCPN** [comment]
SQL missing parenthesis around the OR options in WHERE clause.
