### ISSUE TITLE
Exotic Species Not Sorting Correctly

### ISSUE THREAD

**Issue by envisionnw** [NCPN/upland#82]
Users using upland species drop-downs in the 1-m belt type in species lookup codes.
For 1-m belt drop-downs, typing "b-r-o-t" (_not dashes_) brings up "brotri" versus "brotec" as other drop-downs do.
Point intercept drop-downs properly sort displaying "brotec" as expected.

**Comment by blcampbell-NCPN** [comment]
Closed as previously fixed.
